// src/record-of-power/records.js
// 404TN — Record of Power Seed Records (Tunisia 2019–2026)
// Audited, provenance-backed historical seed records across all core canonical types.

import {
  RECORD_TYPES,
  EPISTEMIC_CLASSIFICATION,
  DATE_PRECISION,
  VERIFICATION_STATUS,
  EVENT_STATUS,
  PROMISE_STATUS,
  LEGAL_STATUS,
  STATEMENT_TYPE,
  OUTCOME_TYPE,
  CAUSATION_STATUS,
  OBSERVATION_TYPE,
  DATA_GAP_STATUS
} from './schema.js';

export const SEED_RECORDS = Object.freeze([
  // ---------------------------------------------------------------------------
  // 1. EVENTS (2019, 2021, 2022, 2024)
  // ---------------------------------------------------------------------------
  {
    id: "ROP-EVT-2019-ELEC-001",
    record_type: RECORD_TYPES.EVENT,
    title: "2019 Presidential Election Second Round Victory of Kais Saied",
    short_title: "2019 Presidential Election",
    summary: "Kais Saied won the second round of the presidential election with 72.71% of the vote (2.77 million ballots) against Nabil Karoui (27.29%) on a 55.02% voter turnout.",
    date_start: "2019-10-13",
    date_end: "2019-10-13",
    date_precision: DATE_PRECISION.EXACT_DAY,
    status: EVENT_STATUS.CONFIRMED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "CRITICAL",
    issue_tags: ["presidency", "governance_institutions", "elections"],
    institution_ids: ["INST-ISIE", "INST-PRESIDENCY"],
    person_ids: ["PERS-KSAIED", "PERS-NKAROUI"],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-ISIE-ELEC2019"],
    evidence_ids: [],
    related_record_ids: ["ROP-PRM-2019-RECON-001", "ROP-PRM-2019-SOV-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Definitive election results validated by ISIE decision n° 2019-27 published in JORT n° 85 (2019)."
  },

  {
    id: "ROP-EVT-2021-0725-001",
    record_type: RECORD_TYPES.EVENT,
    title: "July 25, 2021 Invocation of Article 80 Emergency Measures",
    short_title: "July 25 Emergency Measures",
    summary: "President Kais Saied invoked Article 80 of the 2014 Constitution, suspended parliament (ARP), lifted parliamentary immunity, and dismissed Prime Minister Hichem Mechichi.",
    date_start: "2021-07-25",
    date_end: "2021-07-25",
    date_precision: DATE_PRECISION.EXACT_DAY,
    status: EVENT_STATUS.CONFIRMED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "CRITICAL",
    issue_tags: ["presidency", "constitutional_rupture", "governance_institutions"],
    institution_ids: ["INST-PRESIDENCY", "INST-ARP", "INST-GOV"],
    person_ids: ["PERS-KSAIED", "PERS-HMECHICHI"],
    location_ids: ["LOC-CARTHAGE"],
    source_ids: ["SRC-JORT-DEC117"],
    evidence_ids: [],
    related_record_ids: ["ROP-DEC-2021-0922-001", "ROP-STM-2021-0725-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Enacted via Presidential Decrees 2021-80 and 2021-81 published in JORT n° 64 (2021)."
  },

  {
    id: "ROP-EVT-2024-ELEC-001",
    record_type: RECORD_TYPES.EVENT,
    title: "October 6, 2024 Presidential Election",
    short_title: "2024 Presidential Election",
    summary: "Kais Saied secured re-election with 90.69% of the vote (2.44 million ballots) on an official voter turnout of 28.8% in an election characterized by candidate disqualifications.",
    date_start: "2024-10-06",
    date_end: "2024-10-06",
    date_precision: DATE_PRECISION.EXACT_DAY,
    status: EVENT_STATUS.CONFIRMED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "CRITICAL",
    issue_tags: ["presidency", "elections", "governance_institutions"],
    institution_ids: ["INST-ISIE", "INST-PRESIDENCY", "INST-TA"],
    person_ids: ["PERS-KSAIED", "PERS-AZAMMEL", "PERS-ZMAGHZAOUI"],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-ISIE-ELEC2024"],
    evidence_ids: [],
    related_record_ids: ["ROP-OPP-2024-ISIE-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Definitive results certified by ISIE in JORT (October 2024)."
  },

  // ---------------------------------------------------------------------------
  // 2. PROMISES
  // ---------------------------------------------------------------------------
  {
    id: "ROP-PRM-2019-RECON-001",
    record_type: RECORD_TYPES.PROMISE,
    title: "Penal Reconciliation & 13.5 Billion TND Recovery Pledge",
    short_title: "Penal Reconciliation Pledge",
    summary: "Pledged to recover an estimated 13.5 billion TND from 460 businessmen named in the 2011 Bouderbala anti-corruption report through penal settlements to finance infrastructure in deprived interior delegations.",
    date_start: "2019-10-01",
    date_end: null,
    date_precision: DATE_PRECISION.MONTH,
    status: PROMISE_STATUS.UNRESOLVED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "HIGH",
    issue_tags: ["anti_corruption", "public_finance", "regional_development"],
    institution_ids: ["INST-PRESIDENCY", "INST-MOF"],
    person_ids: ["PERS-KSAIED"],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-MF-DEBT2026Q2"],
    evidence_ids: [],
    related_record_ids: ["ROP-OUT-2026-RECON-001", "ROP-GAP-2026-RECON-RECEIPTS-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Promise made during the 2019 presidential campaign; institutionalized via Decree-Law 2022-13 in March 2022.",
    // Promise-specific fields
    promise_text: "Restitution of 13.5 billion TND in misappropriated public funds from 460 listed businessmen through judicial-financial settlements allocated to the poorest delegations in rank order.",
    speaker: "Kais Saied",
    speaker_role: "Candidate for President of the Republic (2019)",
    promise_date: "2019-10-01",
    policy_area: "CORRUPTION & PUBLIC FINANCE",
    responsible_institution_ids: ["INST-PRESIDENCY", "INST-MOF"],
    deadline_if_any: null,
    action_record_ids: [],
    outcome_record_ids: ["ROP-OUT-2026-RECON-001"],
    status_reason: "Official treasury receipts from penal reconciliation remained below 5% of the 13.5B TND target by mid-2026; committee leadership was replaced repeatedly.",
    unknowns: "Exact disaggregated ledger of individual penal settlement agreements and corporate asset transfers held by the commission."
  },

  {
    id: "ROP-PRM-2019-SOV-001",
    record_type: RECORD_TYPES.PROMISE,
    title: "National Economic Sovereignty & Refusal of Foreign Conditionalities",
    short_title: "Economic Sovereignty Pledge",
    summary: "Pledged that Tunisia would maintain absolute sovereign independence in economic policy, rejecting external dictates, multilateral privatization mandates, and subsidy eliminations.",
    date_start: "2019-10-01",
    date_end: null,
    date_precision: DATE_PRECISION.MONTH,
    status: PROMISE_STATUS.DISPUTED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "HIGH",
    issue_tags: ["economy_public_finance", "sovereignty", "multilateral_loans"],
    institution_ids: ["INST-PRESIDENCY", "INST-MOF", "INST-BCT"],
    person_ids: ["PERS-KSAIED"],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-IMF-PR22353", "SRC-BCT-RATE"],
    evidence_ids: [],
    related_record_ids: ["ROP-IND-GDP-GROWTH-001", "ROP-IND-UNEMP-GRAD-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Core campaign doctrine reiterated in presidential speeches opposing the IMF Extended Fund Facility program in 2023.",
    promise_text: "Tunisia's economic decisions will emerge exclusively from the national will; the state will not sell public enterprises or accept foreign conditionalities that impoverish the people.",
    speaker: "Kais Saied",
    speaker_role: "President of the Republic",
    promise_date: "2019-10-14",
    policy_area: "MACROECONOMIC SOVEREIGNTY",
    responsible_institution_ids: ["INST-PRESIDENCY", "INST-MOF"],
    deadline_if_any: null,
    action_record_ids: [],
    outcome_record_ids: [],
    status_reason: "IMF SLA was frozen, but the state absorbed external loans from bilateral partners and expanded domestic central bank financing (Law 2024-10).",
    unknowns: "Medium-term external debt amortization sustainability without multilateral concessional support."
  },

  // ---------------------------------------------------------------------------
  // 3. DECISIONS
  // ---------------------------------------------------------------------------
  {
    id: "ROP-DEC-2021-0922-001",
    record_type: RECORD_TYPES.DECISION,
    title: "Promulgation of Presidential Decree 117 on Exceptional Measures",
    short_title: "Decree 117 Exceptional Measures",
    summary: "Presidential Decree 117 concentrated legislative and executive powers in the presidency, suspended chapters 1 and 2 of the 2014 Constitution, and established decree-laws as the supreme legislative instrument without judicial review.",
    date_start: "2021-09-22",
    date_end: "2021-09-22",
    date_precision: DATE_PRECISION.EXACT_DAY,
    status: EVENT_STATUS.CONFIRMED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "CRITICAL",
    issue_tags: ["presidency", "constitutional_law", "decree_governance"],
    institution_ids: ["INST-PRESIDENCY", "INST-ARP", "INST-GOV"],
    person_ids: ["PERS-KSAIED"],
    location_ids: ["LOC-CARTHAGE"],
    source_ids: ["SRC-JORT-DEC117"],
    evidence_ids: [],
    related_record_ids: ["ROP-EVT-2021-0725-001", "ROP-LAW-2022-CONST-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Published in JORT n° 86 (Sept 22, 2021).",
    // Decision-specific fields
    decision_type: "PRESIDENTIAL_DECREE",
    decision_maker: "Kais Saied",
    institution: "INST-PRESIDENCY",
    date: "2021-09-22",
    legal_basis: "Article 80 of the 2014 Constitution (Presidential Interpretation)",
    stated_reason: "Preserving state institutions from paralysis, ending political broker corruption, and organizing the transitional path toward a new constitutional referendum.",
    affected_institutions: ["INST-ARP", "INST-GOV", "INST-MOJ"],
    affected_issues: ["governance_institutions", "rights_freedoms"],
    implementation_records: ["ROP-INS-2022-CSM-001", "ROP-DEC-2022-JUDGES-001"],
    outcome_records: ["ROP-LAW-2022-CONST-001"],
    contested_interpretations: "Venice Commission, National Bar Association, and constitutional law scholars disputed the legal basis of suspending the constitution via unilateral decree."
  },

  {
    id: "ROP-DEC-2022-JUDGES-001",
    record_type: RECORD_TYPES.DECISION,
    title: "Executive Revocation of 57 Magistrates via Presidential Decree 516",
    short_title: "Revocation of 57 Judges",
    summary: "Presidential Decree 2022-516 dismissed 57 judges and prosecutors on corruption and moral grounds without prior disciplinary board hearings.",
    date_start: "2022-06-01",
    date_end: "2022-06-01",
    date_precision: DATE_PRECISION.EXACT_DAY,
    status: LEGAL_STATUS.UNEXECUTED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "HIGH",
    issue_tags: ["judiciary", "justice_reform", "rule_of_law"],
    institution_ids: ["INST-PRESIDENCY", "INST-MOJ", "INST-TA", "INST-CSM"],
    person_ids: ["PERS-KSAIED", "PERS-LJEFFAL"],
    location_ids: ["LOC-TUNIS"],
    source_ids: ["SRC-JORT-DEC516"],
    evidence_ids: [],
    related_record_ids: ["ROP-INS-2022-CSM-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Administrative Court suspended the dismissals of 49 judges on August 9, 2022; Ministry of Justice refused execution.",
    decision_type: "PRESIDENTIAL_DECREE",
    decision_maker: "Kais Saied",
    institution: "INST-PRESIDENCY",
    date: "2022-06-01",
    legal_basis: "Decree-Law 2022-35 amending Decree-Law 2022-11 (granting the president dismissal powers)",
    stated_reason: "Cleansing the judicial branch of corruption, financial collusion, and obstruction of political assassination files.",
    affected_institutions: ["INST-MOJ", "INST-CSM", "INST-TA"],
    affected_issues: ["judiciary", "rights_freedoms"],
    implementation_records: [],
    outcome_records: [],
    contested_interpretations: "Administrative Court ruled that dismissals lacked evidentiary substantiation and violated defense rights; executive non-execution created a major institutional impasse."
  },

  // ---------------------------------------------------------------------------
  // 4. LAWS / LEGAL INSTRUMENTS
  // ---------------------------------------------------------------------------
  {
    id: "ROP-LAW-2022-CONST-001",
    record_type: RECORD_TYPES.LAW,
    title: "Constitution of the Republic of Tunisia (2022)",
    short_title: "2022 Constitution",
    summary: "New basic law establishing a centralized presidential system with executive primacy, creating a bicameral parliament, and eliminating presidential impeachment mechanisms.",
    date_start: "2022-07-25",
    date_end: null,
    date_precision: DATE_PRECISION.EXACT_DAY,
    status: LEGAL_STATUS.ENACTED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "CRITICAL",
    issue_tags: ["constitutional_law", "presidency", "governance_institutions"],
    institution_ids: ["INST-PRESIDENCY", "INST-ISIE", "INST-ARP", "INST-NRC"],
    person_ids: ["PERS-KSAIED"],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-JORT-CONST2022"],
    evidence_ids: [],
    related_record_ids: ["ROP-DEC-2021-0922-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Approved via national referendum on July 25, 2022 (94.6% Yes on 30.5% turnout); promulgated in JORT n° 89 (August 17, 2022).",
    // Law-specific fields
    official_title: "Constitution de la République Tunisienne",
    instrument_type: "CONSTITUTION",
    number: "2022",
    publication_date: "2022-08-17",
    effective_date: "2022-08-17",
    jort_reference: "JORT n° 89 du 17 août 2022",
    official_url: "http://www.iort.gov.tn",
    relevant_articles: ["Art. 87-101 (Presidency)", "Art. 56-86 (ARP & NRC)", "Art. 117-124 (Judiciary)"],
    stated_purpose: "Restoring the true revolutionary mandate, eliminating institutional rivalry between parliament and presidency, and guaranteeing the unity of the state.",
    documented_effect: "Centralized all executive, military, and diplomatic authority in the presidency; reduced parliamentary oversight; dismantled independent constitutional bodies.",
    legal_challenges: "Drafting committee chairman Sadok Belaid publicly disavowed the published text; opposition boycotted the referendum.",
    related_court_actions: [],
    affected_rights: ["separation_of_powers", "judicial_independence", "civic_representation"],
    affected_institutions: ["INST-PRESIDENCY", "INST-GOV", "INST-ARP", "INST-NRC", "INST-CSM"]
  },

  {
    id: "ROP-LAW-2022-054-001",
    record_type: RECORD_TYPES.LAW,
    title: "Decree-Law 2022-54 on Combating Cybercrime and Information Offences",
    short_title: "Decree-Law 54",
    summary: "Executive decree-law regulating electronic communications and penalizing the production or dissemination of false news and rumors with up to 5 years imprisonment (10 years if targeting public officials).",
    date_start: "2022-09-13",
    date_end: null,
    date_precision: DATE_PRECISION.EXACT_DAY,
    status: LEGAL_STATUS.ENACTED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "CRITICAL",
    issue_tags: ["press_freedom", "cybercrime", "rights_freedoms", "judiciary"],
    institution_ids: ["INST-PRESIDENCY", "INST-MOJ", "INST-MOI"],
    person_ids: ["PERS-KSAIED", "PERS-LJEFFAL"],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-JORT-DEC54"],
    evidence_ids: [],
    related_record_ids: [],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Published in JORT n° 103 (Sept 13, 2022). Over 60 journalists, attorneys, and political opposition figures prosecuted under Article 24.",
    official_title: "Décret-loi n° 2022-54 du 13 septembre 2022, relatif à la lutte contre les infractions se rapportant aux systèmes d'information et de communication",
    instrument_type: "DECREE_LAW",
    number: "2022-54",
    publication_date: "2022-09-13",
    effective_date: "2022-09-13",
    jort_reference: "JORT n° 103 du 13 septembre 2022",
    official_url: "http://www.iort.gov.tn",
    relevant_articles: ["Article 24 (False news & defamation penalties)"],
    stated_purpose: "Protecting citizens and state institutions from digital defamation, fraudulent cybercrime, and weaponized disinformation.",
    documented_effect: "Substantial increase in criminal prosecutions against critical journalists (SNJT documentation), opposition politicians, and social media commentators.",
    legal_challenges: "National Bar Association and National Syndicate of Tunisian Journalists (SNJT) filed administrative and legal appeals challenging constitutionality under Article 37 (Freedom of expression).",
    related_court_actions: [],
    affected_rights: ["freedom_of_expression", "press_freedom", "digital_privacy"],
    affected_institutions: ["INST-MOJ", "INST-MOI"]
  },

  // ---------------------------------------------------------------------------
  // 5. INSTITUTIONAL CHANGES
  // ---------------------------------------------------------------------------
  {
    id: "ROP-INS-2022-CSM-001",
    record_type: RECORD_TYPES.INSTITUTIONAL_CHANGE,
    title: "Dissolution of the Elected High Judicial Council (CSM)",
    short_title: "Dissolution of CSM",
    summary: "President Kais Saied dissolved the constitutionally elected High Judicial Council via Decree-Law 2022-11 and established a Provisional High Judicial Council with members appointed directly by the presidency.",
    date_start: "2022-02-12",
    date_end: "2022-02-12",
    date_precision: DATE_PRECISION.EXACT_DAY,
    status: EVENT_STATUS.CONFIRMED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "CRITICAL",
    issue_tags: ["judiciary", "governance_institutions", "rule_of_law"],
    institution_ids: ["INST-PRESIDENCY", "INST-CSM", "INST-MOJ"],
    person_ids: ["PERS-KSAIED"],
    location_ids: ["LOC-TUNIS"],
    source_ids: ["SRC-JORT-DEC516"],
    evidence_ids: [],
    related_record_ids: ["ROP-DEC-2022-JUDGES-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Promulgated in JORT n° 16 (Feb 12, 2022)."
  },

  // ---------------------------------------------------------------------------
  // 6. OFFICIAL STATEMENTS & OPPOSITION CLAIMS
  // ---------------------------------------------------------------------------
  {
    id: "ROP-STM-2021-0725-001",
    record_type: RECORD_TYPES.OFFICIAL_STATEMENT,
    title: "Presidential Address Declaring Emergency State Protection",
    short_title: "July 25 Presidential Address",
    summary: "President Kais Saied stated from Carthage Palace that the exceptional measures were taken to save the Tunisian state from imminent danger and collapse in strict application of Article 80.",
    date_start: "2021-07-25",
    date_end: "2021-07-25",
    date_precision: DATE_PRECISION.EXACT_DAY,
    status: EVENT_STATUS.CONFIRMED,
    classification: EPISTEMIC_CLASSIFICATION.CLAIM,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "HIGH",
    issue_tags: ["presidency", "article80", "official_discourse"],
    institution_ids: ["INST-PRESIDENCY"],
    person_ids: ["PERS-KSAIED"],
    location_ids: ["LOC-CARTHAGE"],
    source_ids: ["SRC-JORT-DEC117"],
    evidence_ids: [],
    related_record_ids: ["ROP-EVT-2021-0725-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Broadcast live on Télévision Tunisienne 1 and published on official presidency portal.",
    // Statement-specific fields
    speaker: "Kais Saied",
    speaker_role: "President of the Republic",
    institution: "INST-PRESIDENCY",
    date: "2021-07-25",
    statement_text_or_summary: "We have taken these decisions until social peace returns to the country and until we save the state... whoever shoots a bullet, our armed forces will respond with a hail of bullets.",
    statement_type: STATEMENT_TYPE.JUSTIFICATION,
    verification_status: VERIFICATION_STATUS.VERIFIED
  },

  {
    id: "ROP-OPP-2024-ISIE-001",
    record_type: RECORD_TYPES.OPPOSITION_CLAIM,
    title: "Opposition Coalition Challenge on Electoral Disqualifications",
    short_title: "2024 Election Disqualification Challenge",
    summary: "Opposition political parties and candidates asserted that the ISIE's refusal to enforce Administrative Court reinstatement rulings violated electoral fairness and constitutional standards.",
    date_start: "2024-09-02",
    date_end: "2024-10-06",
    date_precision: DATE_PRECISION.RANGE,
    status: EVENT_STATUS.CONTESTED,
    classification: EPISTEMIC_CLASSIFICATION.CLAIM,
    verification_status: VERIFICATION_STATUS.VERIFIED_WITH_QUALIFICATION,
    importance: "HIGH",
    issue_tags: ["elections", "opposition", "judiciary", "isie"],
    institution_ids: ["INST-ISIE", "INST-TA"],
    person_ids: ["PERS-KSAIED", "PERS-AZAMMEL", "PERS-MDAYMI"],
    location_ids: ["LOC-TUNIS"],
    source_ids: ["SRC-ISIE-ELEC2024"],
    evidence_ids: [],
    related_record_ids: ["ROP-EVT-2024-ELEC-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Administrative Court issued final appellate rulings reinstating candidates (Daimi, Znaidi, Mekki); ISIE rejected the rulings claiming late notification."
  },

  // ---------------------------------------------------------------------------
  // 7. OUTCOMES & INDICATORS
  // ---------------------------------------------------------------------------
  {
    id: "ROP-OUT-2026-RECON-001",
    record_type: RECORD_TYPES.OUTCOME,
    title: "Penal Reconciliation Treasury Receipts Performance (2022–2026)",
    short_title: "Penal Reconciliation Receipts",
    summary: "Total official financial recovery through the National Penal Reconciliation Commission remained under 500 million TND (<5% of the 13.5 billion TND target) by Summer 2026.",
    date_start: "2022-03-20",
    date_end: "2026-06-30",
    date_precision: DATE_PRECISION.RANGE,
    status: EVENT_STATUS.CONFIRMED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED_WITH_QUALIFICATION,
    importance: "HIGH",
    issue_tags: ["public_finance", "anti_corruption", "budget_deficits"],
    institution_ids: ["INST-MOF", "INST-PRESIDENCY"],
    person_ids: [],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-MF-DEBT2026Q2"],
    evidence_ids: [],
    related_record_ids: ["ROP-PRM-2019-RECON-001", "ROP-GAP-2026-RECON-RECEIPTS-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Ministry of Finance budget execution reports (2022–2026) document actual treasury penal reconciliation account receipts.",
    outcome_type: OUTCOME_TYPE.MEASURED_OUTCOME,
    result: "Receipts below 5% of target; no major regional infrastructure projects financed from dedicated penal funds.",
    reference_period: "2022–2026",
    measurement: "<500M TND (<5%)",
    unit: "TND / % of Target",
    baseline: "13,500M TND Target",
    comparison: "Actual receipts represent less than 1/20th of pledged sovereign recovery.",
    causation_status: CAUSATION_STATUS.ESTABLISHED
  },

  {
    id: "ROP-OUT-2026-WATER-001",
    record_type: RECORD_TYPES.OUTCOME,
    title: "Potable Water Rationing & Hydraulic Stress in Summer 2026",
    short_title: "2026 Potable Water Rationing",
    summary: "National dam reservoir saturation dropped to ~21.4% following consecutive drought years; SONEDE maintained night-time potable water cuts across urban and rural governorates.",
    date_start: "2026-06-01",
    date_end: "2026-08-31",
    date_precision: DATE_PRECISION.RANGE,
    status: EVENT_STATUS.ONGOING,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "HIGH",
    issue_tags: ["water", "public_services", "infrastructure", "climate_drought"],
    institution_ids: ["INST-SONEDE", "INST-MOA"],
    person_ids: [],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-INS-ACC2026Q2"],
    evidence_ids: [],
    related_record_ids: [],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Drought and hydraulic deficits stem from climatic conditions compounded by multi-year pipe leakage rates (~30%) and delayed desalination infrastructure.",
    outcome_type: OUTCOME_TYPE.SERVICE_OUTCOME,
    result: "Night-time water rationing operational in 20+ governorates.",
    reference_period: "Summer 2026",
    measurement: "21.4% Dam Saturation",
    unit: "% Reservoir Capacity",
    baseline: "45–55% Historical Normal",
    comparison: "Lowest dam reserve levels recorded in over a decade.",
    causation_status: CAUSATION_STATUS.SUPPORTED_ASSOCIATION
  },

  {
    id: "ROP-IND-UNEMP-GRAD-001",
    record_type: RECORD_TYPES.INDICATOR,
    title: "Higher Education Graduate Unemployment Rate (2019 vs 2026)",
    short_title: "Graduate Unemployment Indicator",
    summary: "Higher education graduate unemployment expanded from 28.0% in Q2 2019 to 38.8% in Q2 2026, documenting intense labor market stagnation for educated youth.",
    date_start: "2019-06-30",
    date_end: "2026-06-30",
    date_precision: DATE_PRECISION.RANGE,
    status: EVENT_STATUS.CONFIRMED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "HIGH",
    issue_tags: ["labor_market", "unemployment", "youth_drain", "economy"],
    institution_ids: ["INST-INS"],
    person_ids: [],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-INS-EMP2019", "SRC-INS-EMP2026Q2"],
    evidence_ids: [],
    related_record_ids: [],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "INS Enquête Nationale sur l'Emploi quarterly survey datasets.",
    // Indicator-specific fields
    indicator_id: "ROP-IND-UNEMP-GRAD-001",
    name: "Higher Education Graduate Unemployment Rate",
    category: "LABOR",
    value: "38.8%",
    unit: "% of Active University Graduates",
    reference_period: "Q2 2026",
    observation_type: OBSERVATION_TYPE.QUARTERLY,
    methodology: "INS National Labour Force Survey probability sample across all 24 governorates",
    geographic_scope: "NATIONAL",
    population_scope: "Higher Education Graduates (Ages 20–35+)",
    comparable_to_ids: ["SRC-INS-EMP2019"],
    comparability_notes: "Strictly comparable quarterly survey methodology maintained by INS."
  },

  {
    id: "ROP-IND-GDP-GROWTH-001",
    record_type: RECORD_TYPES.INDICATOR,
    title: "Real GDP Growth Rate (2019 Baseline vs 2026 Preliminary)",
    short_title: "Real GDP Growth Indicator",
    summary: "Annualized real economic growth recorded +0.8% year-on-year in Q2 2026 compared to +1.5% in 2019.",
    date_start: "2026-04-01",
    date_end: "2026-06-30",
    date_precision: DATE_PRECISION.RANGE,
    status: EVENT_STATUS.CONFIRMED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED_WITH_QUALIFICATION,
    importance: "HIGH",
    issue_tags: ["macroeconomics", "gdp", "economic_growth"],
    institution_ids: ["INST-INS"],
    person_ids: [],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-INS-ACC2019", "SRC-INS-ACC2026Q2"],
    evidence_ids: [],
    related_record_ids: [],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "2019 is full-year actual; 2026 is preliminary quarterly year-on-year from INS Comptes Nationaux Trimestriels.",
    indicator_id: "ROP-IND-GDP-GROWTH-001",
    name: "Real GDP Growth Rate (YoY)",
    category: "GROWTH",
    value: "+0.8%",
    unit: "% Year-on-Year",
    reference_period: "Q2 2026",
    observation_type: OBSERVATION_TYPE.PRELIMINARY,
    methodology: "INS Quarterly National Accounts (Base 2015)",
    geographic_scope: "NATIONAL",
    population_scope: "Total Economy",
    comparable_to_ids: ["SRC-INS-ACC2019"],
    comparability_notes: "2019 represents completed annual series; 2026 represents preliminary quarterly annualized rate."
  },

  // ---------------------------------------------------------------------------
  // 8. DATA GAPS
  // ---------------------------------------------------------------------------
  {
    id: "ROP-GAP-2026-GABES-AIR-001",
    record_type: RECORD_TYPES.DATA_GAP,
    title: "Continuous Ambient Air & Marine Quality Telemetry for Gabès Industrial Zone",
    short_title: "Gabès Continuous Environmental Telemetry Gap",
    summary: "Real-time continuous sensor readings for sulfur dioxide (SO2), fluoride, and coastal phosphogypsum dispersion in the Gulf of Gabès are not publicly published by state agencies.",
    date_start: "2018-01-01",
    date_end: null,
    date_precision: DATE_PRECISION.ONGOING,
    status: DATA_GAP_STATUS.NOT_PUBLISHED,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "CRITICAL",
    issue_tags: ["pollution", "gabes", "environmental_transparency", "public_health"],
    institution_ids: ["INST-ANPE", "INST-MOENV", "INST-GCT"],
    person_ids: [],
    location_ids: ["LOC-GABES-CHATT-ESSALEM"],
    source_ids: ["SRC-ANPE-GABES2018"],
    evidence_ids: [],
    related_record_ids: [],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "404TN audited existing ANPE and World Bank documents; continuous operational sensor feeds could not be identified on public open data portals.",
    // Data gap fields
    missing_information: "Real-time automated hourly ambient air emissions (SO2, NH3, particulate matter) and marine chemical discharge telemetry in Gabès.",
    institution_expected_to_hold_data: "INST-ANPE (Agence Nationale de Protection de l'Environnement)",
    why_it_matters: "Prevents independent epidemiological verification of toxic pollutant exposure on local residential populations in Chatt Essalem and Bouchamma.",
    latest_available_period: "2018 (World Bank PGSE Audit)",
    search_or_request_status: "Formally requested via access-to-information framework; unpublished on open data portals.",
    data_gap_status: DATA_GAP_STATUS.NOT_PUBLISHED
  },

  {
    id: "ROP-GAP-2026-RECON-RECEIPTS-001",
    record_type: RECORD_TYPES.DATA_GAP,
    title: "Disaggregated Ledger of Settlements by the Penal Reconciliation Commission",
    short_title: "Penal Reconciliation Itemized Ledger Gap",
    summary: "The specific itemized register of penal settlements, identities of settling corporations, and regional escrow allocations has not been made public.",
    date_start: "2022-03-20",
    date_end: null,
    date_precision: DATE_PRECISION.ONGOING,
    status: DATA_GAP_STATUS.INACCESSIBLE,
    classification: EPISTEMIC_CLASSIFICATION.FACT,
    verification_status: VERIFICATION_STATUS.VERIFIED,
    importance: "HIGH",
    issue_tags: ["anti_corruption", "public_finance", "penal_reconciliation"],
    institution_ids: ["INST-PRESIDENCY", "INST-MOF"],
    person_ids: [],
    location_ids: ["LOC-TUNISIA-NAT"],
    source_ids: ["SRC-MF-DEBT2026Q2"],
    evidence_ids: [],
    related_record_ids: ["ROP-PRM-2019-RECON-001", "ROP-OUT-2026-RECON-001"],
    created_at: "2026-09-11T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
    editorial_notes: "Only aggregate treasury account balance is disclosed in general budget execution notes.",
    missing_information: "Case-by-case accounting of negotiated settlement values, signed agreements, and actual cash/asset transfers.",
    institution_expected_to_hold_data: "INST-PRESIDENCY (Commission Nationale de Réconciliation Pénale) & INST-MOF",
    why_it_matters: "Essential to audit the financial efficacy and non-partisan equity of the reconciliation mechanism.",
    latest_available_period: "June 2026",
    search_or_request_status: "Commission deliberations are classified confidential under Decree-Law 2022-13.",
    data_gap_status: DATA_GAP_STATUS.INACCESSIBLE
  }
]);
