// src/record-of-power/schema.js
// 404TN — Record of Power (Tunisia 2019–2026) Canonical Schemas & Enumerations

/**
 * 1. CORE RECORD TYPES
 */
export const RECORD_TYPES = Object.freeze({
  EVENT: "EVENT",
  PROMISE: "PROMISE",
  DECISION: "DECISION",
  LAW: "LAW",
  INSTITUTIONAL_CHANGE: "INSTITUTIONAL_CHANGE",
  OFFICIAL_STATEMENT: "OFFICIAL_STATEMENT",
  OPPOSITION_CLAIM: "OPPOSITION_CLAIM",
  OUTCOME: "OUTCOME",
  INDICATOR: "INDICATOR",
  EVIDENCE_LINK: "EVIDENCE_LINK",
  DATA_GAP: "DATA_GAP"
});

/**
 * 2. EPISTEMIC CLASSIFICATION
 * Political position remains strictly separate from factual classification.
 */
export const EPISTEMIC_CLASSIFICATION = Object.freeze({
  FACT: "FACT",         // Directly supported by official/empirical evidence
  CLAIM: "CLAIM",       // Attributed statement or allegation not independently established as fact
  ANALYSIS: "ANALYSIS"  // 404TN investigative interpretation of documented evidence
});

/**
 * 3. DATE PRECISION
 */
export const DATE_PRECISION = Object.freeze({
  EXACT_DAY: "EXACT_DAY",
  MONTH: "MONTH",
  YEAR: "YEAR",
  RANGE: "RANGE",
  ONGOING: "ONGOING"
});

/**
 * 4. VERIFICATION STATUS
 */
export const VERIFICATION_STATUS = Object.freeze({
  VERIFIED: "VERIFIED",
  VERIFIED_WITH_QUALIFICATION: "VERIFIED_WITH_QUALIFICATION",
  CONTESTED: "CONTESTED",
  UNVERIFIED: "UNVERIFIED"
});

/**
 * 5. RECORD STATUSES (TYPE-SPECIFIC)
 */
export const EVENT_STATUS = Object.freeze({
  CONFIRMED: "CONFIRMED",
  ONGOING: "ONGOING",
  CLOSED: "CLOSED",
  CONTESTED: "CONTESTED"
});

export const PROMISE_STATUS = Object.freeze({
  PROMISED: "PROMISED",
  ACTION_STARTED: "ACTION_STARTED",
  PARTIAL: "PARTIAL",
  FULFILLED: "FULFILLED",
  UNRESOLVED: "UNRESOLVED",
  ABANDONED: "ABANDONED",
  DISPUTED: "DISPUTED"
});

export const LEGAL_STATUS = Object.freeze({
  ALLEGED: "ALLEGED",
  INVESTIGATED: "INVESTIGATED",
  CHARGED: "CHARGED",
  TRIED: "TRIED",
  CONVICTED: "CONVICTED",
  ACQUITTED: "ACQUITTED",
  DISMISSED: "DISMISSED",
  STAYED: "STAYED",
  APPEALED: "APPEALED",
  ENACTED: "ENACTED",
  UNEXECUTED: "UNEXECUTED"
});

export const STATEMENT_TYPE = Object.freeze({
  POLICY_ANNOUNCEMENT: "POLICY_ANNOUNCEMENT",
  JUSTIFICATION: "JUSTIFICATION",
  ALLEGATION: "ALLEGATION",
  DENIAL: "DENIAL",
  COMMITMENT: "COMMITMENT",
  RESPONSE: "RESPONSE",
  ASSESSMENT: "ASSESSMENT"
});

export const OUTCOME_TYPE = Object.freeze({
  MEASURED_OUTCOME: "MEASURED_OUTCOME",
  ADMINISTRATIVE_OUTCOME: "ADMINISTRATIVE_OUTCOME",
  LEGAL_OUTCOME: "LEGAL_OUTCOME",
  POLITICAL_OUTCOME: "POLITICAL_OUTCOME",
  SERVICE_OUTCOME: "SERVICE_OUTCOME",
  ECONOMIC_OUTCOME: "ECONOMIC_OUTCOME",
  UNKNOWN_OUTCOME: "UNKNOWN_OUTCOME"
});

export const CAUSATION_STATUS = Object.freeze({
  ESTABLISHED: "ESTABLISHED",
  SUPPORTED_ASSOCIATION: "SUPPORTED_ASSOCIATION",
  PLAUSIBLE_BUT_UNPROVEN: "PLAUSIBLE_BUT_UNPROVEN",
  NOT_ESTABLISHED: "NOT_ESTABLISHED",
  NOT_APPLICABLE: "NOT_APPLICABLE"
});

export const OBSERVATION_TYPE = Object.freeze({
  ANNUAL_ACTUAL: "ANNUAL_ACTUAL",
  QUARTERLY: "QUARTERLY",
  MONTHLY: "MONTHLY",
  YEAR_TO_DATE: "YEAR_TO_DATE",
  DAILY: "DAILY",
  PRELIMINARY: "PRELIMINARY",
  ESTIMATE: "ESTIMATE",
  FORECAST: "FORECAST"
});

export const DATA_GAP_STATUS = Object.freeze({
  NOT_PUBLISHED: "NOT_PUBLISHED",
  OUTDATED: "OUTDATED",
  INCOMPLETE: "INCOMPLETE",
  INACCESSIBLE: "INACCESSIBLE",
  METHODOLOGY_UNKNOWN: "METHODOLOGY_UNKNOWN",
  REQUESTED: "REQUESTED",
  RESOLVED: "RESOLVED"
});

export const RESPONSIBILITY_TYPE = Object.freeze({
  POLICY_AUTHORITY: "POLICY_AUTHORITY",
  IMPLEMENTATION_AUTHORITY: "IMPLEMENTATION_AUTHORITY",
  REGULATORY_AUTHORITY: "REGULATORY_AUTHORITY",
  BUDGET_AUTHORITY: "BUDGET_AUTHORITY",
  OVERSIGHT_AUTHORITY: "OVERSIGHT_AUTHORITY",
  JUDICIAL_AUTHORITY: "JUDICIAL_AUTHORITY",
  SERVICE_DELIVERY: "SERVICE_DELIVERY",
  DATA_PUBLICATION: "DATA_PUBLICATION"
});

/**
 * 6. RELATIONSHIP TYPES
 */
export const RELATIONSHIP_TYPE = Object.freeze({
  PROMISE_FOLLOWED_BY_ACTION: "PROMISE_FOLLOWED_BY_ACTION",
  DECISION_AUTHORIZED_BY_LAW: "DECISION_AUTHORIZED_BY_LAW",
  DECISION_AFFECTED_INSTITUTION: "DECISION_AFFECTED_INSTITUTION",
  ACTION_PRODUCED_OUTCOME: "ACTION_PRODUCED_OUTCOME",
  OUTCOME_MEASURED_BY_INDICATOR: "OUTCOME_MEASURED_BY_INDICATOR",
  EVENT_TRIGGERED_DECISION: "EVENT_TRIGGERED_DECISION",
  STATEMENT_REFERS_TO_EVENT: "STATEMENT_REFERS_TO_EVENT",
  EVIDENCE_SUPPORTS_RECORD: "EVIDENCE_SUPPORTS_RECORD",
  EVIDENCE_CONTRADICTS_CLAIM: "EVIDENCE_CONTRADICTS_CLAIM",
  INSTITUTION_RESPONSIBLE_FOR: "INSTITUTION_RESPONSIBLE_FOR",
  RECORD_SUPERSEDES_RECORD: "RECORD_SUPERSEDES_RECORD",
  RECORD_DISPUTES_RECORD: "RECORD_DISPUTES_RECORD",
  DATA_GAP_APPLIES_TO: "DATA_GAP_APPLIES_TO"
});
