// src/record-of-power/sources.js
// 404TN — Primary Source Manifest for Record of Power

export const SOURCE_MANIFEST = Object.freeze([
  {
    "source_id": "SRC-INS-ACC2019",
    "organization": "National Institute of Statistics (INS)",
    "title": "Comptes Nationaux Annuels 2019",
    "publication_date": "2020-05-15",
    "reference_period": "2019 Full Year",
    "url": "http://www.ins.tn/statistiques/economie/comptes-nationaux",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Official 2019 real GDP growth rate (+1.5%)."
  },
  {
    "source_id": "SRC-INS-ACC2026Q2",
    "organization": "National Institute of Statistics (INS)",
    "title": "Comptes Nationaux Trimestriels - Deuxième Trimestre 2026",
    "publication_date": "2026-08-15",
    "reference_period": "Q2 2026",
    "url": "http://www.ins.tn/publication/croissance-economique-t2-2026",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Official Q2 2026 real GDP growth rate (+2.3% YoY, +1.4% QoQ)."
  },
  {
    "source_id": "SRC-INS-EMP2019",
    "organization": "National Institute of Statistics (INS)",
    "title": "Enquête Nationale sur l'Emploi - Résultats du Deuxième Trimestre 2019",
    "publication_date": "2019-08-15",
    "reference_period": "Q2 2019",
    "url": "http://www.ins.tn/publication/enquete-nationale-sur-lemploi-t2-2019",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Overall unemployment baseline 14.9% (634.9k unemployed) and graduate unemployment 28.0%."
  },
  {
    "source_id": "SRC-INS-EMP2026Q2",
    "organization": "National Institute of Statistics (INS)",
    "title": "Enquête Nationale sur l'Emploi - Résultats du Deuxième Trimestre 2026",
    "publication_date": "2026-08-15",
    "reference_period": "Q2 2026",
    "url": "http://www.ins.tn/publication/enquete-nationale-sur-lemploi-t2-2026",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Official Q2 2026 higher-education graduate unemployment rate (26.6% overall; 14.2% male, 35.6% female; Q1 was 24.2%)."
  },
  {
    "source_id": "SRC-INS-IPC2019",
    "organization": "National Institute of Statistics (INS)",
    "title": "Indice des Prix à la Consommation - Décembre 2019",
    "publication_date": "2020-01-05",
    "reference_period": "Annual 2019",
    "url": "http://www.ins.tn/publication/indice-des-prix-la-consommation-ipc-decembre-2019",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Annual average headline consumer inflation at 6.7%."
  },
  {
    "source_id": "SRC-INS-IPC202608",
    "organization": "National Institute of Statistics (INS)",
    "title": "Indice des Prix à la Consommation - Août 2026",
    "publication_date": "2026-09-05",
    "reference_period": "August 2026",
    "url": "http://www.ins.tn/publication/indice-des-prix-la-consommation-ipc-aout-2026",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Official August 2026 consumer price index: headline inflation 5.4% YoY, food and non-alcoholic beverages 7.5% YoY."
  },
  {
    "source_id": "SRC-MF-DEBT2019",
    "organization": "Ministry of Finance",
    "title": "Rapport sur la Dette Publique - Exercice 2019",
    "publication_date": "2020-06-30",
    "reference_period": "End 2019",
    "url": "http://www.finances.gov.tn/fr/statistiques/dette-publique-2019",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Total public debt reached 67.8% of GDP (83.3 billion TND)."
  },
  {
    "source_id": "SRC-MF-DEBT2026Q2",
    "organization": "Ministry of Finance",
    "title": "Résultats de l'Exécution du Budget et Encours de la Dette Publique (Juin 2026)",
    "publication_date": "2026-08-20",
    "reference_period": "End June 2026",
    "url": "http://www.finances.gov.tn/fr/statistiques/execution-budget-juin-2026",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Total public debt reached 80.2% of GDP."
  },
  {
    "source_id": "SRC-BCT-RATE",
    "organization": "Banque Centrale de Tunisie (BCT)",
    "title": "Décisions du Conseil d'Administration de la BCT sur le Taux Directeur",
    "publication_date": "2026-07-31",
    "reference_period": "2019–2026",
    "url": "https://www.bct.gov.tn/bct/site-box/taux_directeur.jsp",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Policy rate: 7.75% in 2019; maintained at 8.00% through Summer 2026."
  },
  {
    "source_id": "SRC-BCT-FX2026",
    "organization": "Banque Centrale de Tunisie (BCT)",
    "title": "Indicateurs Monétaires et Financiers Quotidiens",
    "publication_date": "2026-08-31",
    "reference_period": "August 2026",
    "url": "https://www.bct.gov.tn/bct/site-box/indicateurs_quotidiens.jsp",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Net foreign exchange reserves at 112 days of imports (24.8 billion TND)."
  },
  {
    "source_id": "SRC-ONME-DEF2026",
    "organization": "National Energy Observatory (ONME / Ministry of Energy)",
    "title": "Conjoncture Énergétique Mensuelle - Bilan Énergétique National",
    "publication_date": "2026-08-10",
    "reference_period": "Mid-2026",
    "url": "http://www.energiemines.gov.tn/observatoire/conjoncture-energetique",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Primary energy balance deficit at 52% (compared to 49% in 2019)."
  },
  {
    "source_id": "SRC-ISIE-ELEC2019",
    "organization": "Instance Supérieure Indépendante pour les Élections (ISIE)",
    "title": "Décision de l'ISIE n° 2019-27 fixant les résultats définitifs de l'élection présidentielle 2019",
    "publication_date": "2019-10-17",
    "reference_period": "October 13, 2019",
    "url": "http://www.isie.tn/resultats-presidentielle-2019",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "ar",
    "notes": "Kais Saied won second round with 72.71% (2,777,931 votes) vs Nabil Karoui 27.29% (1,042,894 votes). Published in JORT n° 85 (2019)."
  },
  {
    "source_id": "SRC-ISIE-ELEC2024",
    "organization": "Instance Supérieure Indépendante pour les Élections (ISIE)",
    "title": "Décision de l'ISIE relative aux résultats définitifs de l'élection présidentielle du 6 octobre 2024",
    "publication_date": "2024-10-11",
    "reference_period": "October 6, 2024",
    "url": "http://www.isie.tn/resultats-presidentielle-2024",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "ar",
    "notes": "Kais Saied re-elected with 90.69% (2,438,954 votes) on 28.8% turnout. Published in JORT (2024)."
  },
  {
    "source_id": "SRC-JORT-DEC117",
    "organization": "Presidency of the Republic of Tunisia",
    "title": "Décret présidentiel n° 2021-117 du 22 septembre 2021, relatif aux mesures exceptionnelles",
    "publication_date": "2021-09-22",
    "reference_period": "September 22, 2021",
    "url": "http://www.iort.gov.tn/WD120AWP/WD120Awm.exe/CTX_4896-1-UjDqGkXhWw/AfficheSommaire/SYNC_1843936663",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Established plenary presidential decree authority, suspended chapter 1 & 2 of 2014 Constitution conflicting with decree powers, abolished provisional constitutional review instance."
  },
  {
    "source_id": "SRC-JORT-CONST2022",
    "organization": "Presidency of the Republic / ISIE",
    "title": "Constitution de la République Tunisienne adoptée par référendum le 25 juillet 2022",
    "publication_date": "2022-08-17",
    "reference_period": "July 25, 2022",
    "url": "http://www.iort.gov.tn/WD120AWP/WD120Awm.exe/CTX_4896-1-UjDqGkXhWw/AfficheSommaire/SYNC_2022_89",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Promulgated in JORT n° 89. Adopted with 94.6% yes votes on 30.5% turnout. Replaces 2014 Constitution."
  },
  {
    "source_id": "SRC-JORT-DEC54",
    "organization": "Presidency of the Republic",
    "title": "Décret-loi n° 2022-54 du 13 septembre 2022, relatif à la lutte contre les infractions se rapportant aux systèmes d'information et de communication",
    "publication_date": "2022-09-13",
    "reference_period": "September 13, 2022",
    "url": "http://www.iort.gov.tn/WD120AWP/WD120Awm.exe/CTX_4896-1-UjDqGkXhWw/AfficheSommaire/SYNC_2022_103",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Article 24 establishes 5-year prison terms (10 years if public official targeted) for spreading false news."
  },
  {
    "source_id": "SRC-JORT-DEC516",
    "organization": "Presidency of the Republic",
    "title": "Décret présidentiel n° 2022-516 du 1er juin 2022, portant révocation de magistrats",
    "publication_date": "2022-06-01",
    "reference_period": "June 1, 2022",
    "url": "http://www.iort.gov.tn/WD120AWP/WD120Awm.exe/CTX_4896-1-UjDqGkXhWw/AfficheSommaire/SYNC_2022_60",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Executive revocation of 57 magistrates. Administrative Court suspended dismissals for 49 judges on Aug 9, 2022."
  },
  {
    "source_id": "SRC-MOODYS-2024",
    "organization": "Moody's Investors Service",
    "title": "Credit Opinion: Government of Tunisia - Caa2 Stable",
    "publication_date": "2024-03-22",
    "reference_period": "2024–2026",
    "url": "https://www.moodys.com/research/Moodys-affirms-Tunisias-Caa2-ratings-maintains-stable-outlook--PR_486790",
    "source_type": "INDEPENDENT",
    "accessed_at": "2026-09-11",
    "language": "en",
    "notes": "Affirmed Caa2 rating with Stable outlook."
  },
  {
    "source_id": "SRC-FITCH-2024",
    "organization": "Fitch Ratings",
    "title": "Fitch Upgrades Tunisia to 'CCC+'",
    "publication_date": "2024-03-29",
    "reference_period": "2024–2026",
    "url": "https://www.fitchratings.com/research/sovereigns/fitch-upgrades-tunisia-to-ccc-plus-29-03-2024",
    "source_type": "INDEPENDENT",
    "accessed_at": "2026-09-11",
    "language": "en",
    "notes": "Upgraded sovereign credit rating from CCC- to CCC+."
  },
  {
    "source_id": "SRC-AB-WAVEV",
    "organization": "Arab Barometer",
    "title": "Arab Barometer Wave V: Tunisia Country Report",
    "publication_date": "2019-06-24",
    "reference_period": "Oct 26, 2018 – Jan 5, 2019",
    "url": "https://www.arabbarometer.org/countries/tunisia/",
    "source_type": "ACADEMIC",
    "accessed_at": "2026-09-11",
    "language": "en",
    "notes": "n=2,400 face-to-face probability sample. ±2.5% margin of error. Trust in president: 18%; trust in gov: 18%; trust in parliament: 14%; trust in police: 65%; youth migration intent: 42%."
  },
  {
    "source_id": "SRC-AB-WAVEVII",
    "organization": "Arab Barometer",
    "title": "Arab Barometer Wave VII: Tunisia Country Report - Public Opinion After July 25",
    "publication_date": "2022-06-20",
    "reference_period": "Feb 14 – Mar 24, 2022",
    "url": "https://www.arabbarometer.org/surveys/tunisia-survey-wave-vii/",
    "source_type": "ACADEMIC",
    "accessed_at": "2026-09-11",
    "language": "en",
    "notes": "n=2,424 face-to-face probability sample. ±2.5% margin of error. Trust in Kais Saied: 62%; trust in gov: 39%; trust in parliament: 12%; trust in police: 67%; youth migration intent: 46%."
  },
  {
    "source_id": "SRC-AB-WAVEVIII",
    "organization": "Arab Barometer",
    "title": "Arab Barometer Wave VIII: Tunisia Country Report - Views on Governance and Economy",
    "publication_date": "2024-05-14",
    "reference_period": "Dec 11, 2023 – Jan 23, 2024",
    "url": "https://www.arabbarometer.org/surveys/arab-barometer-wave-viii-tunisia/",
    "source_type": "ACADEMIC",
    "accessed_at": "2026-09-11",
    "language": "en",
    "notes": "n=2,406 face-to-face probability sample. ±2.5% margin of error. Trust in Kais Saied: 43%; trust in gov: 25%; trust in parliament: 18%; trust in police: 61%; youth migration intent (18-29): 53%; economic condition good: 6%."
  },
  {
    "source_id": "SRC-EU-MOU2023",
    "organization": "European Commission / Republic of Tunisia",
    "title": "Memorandum of Understanding on a Strategic and Global Partnership between the European Union and Tunisia",
    "publication_date": "2023-07-16",
    "reference_period": "July 16, 2023",
    "url": "https://ec.europa.eu/commission/presscorner/detail/en/ip_23_3887",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "en",
    "notes": "Signed in Tunis. €105M for border management and anti-smuggling; €150M in direct budgetary assistance disbursed March 2024."
  },
  {
    "source_id": "SRC-IMF-PR22353",
    "organization": "International Monetary Fund (IMF)",
    "title": "IMF Staff Reaches Staff-Level Agreement on an Extended Fund Facility with Tunisia",
    "publication_date": "2022-10-15",
    "reference_period": "October 15, 2022",
    "url": "https://www.imf.org/en/News/Articles/2022/10/15/pr22353-tunisia-imf-staff-reaches-staff-level-agreement-on-an-extended-fund-facility",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "en",
    "notes": "48-month EFF arrangement for SDR 1.472 billion (~$1.9 billion). Execution stalled without Executive Board submission."
  },
  {
    "source_id": "SRC-WB-ELMED2023",
    "organization": "World Bank Group / STEG / Terna",
    "title": "Tunisia-Italy Power Interconnector - ELMED Project (P179247)",
    "publication_date": "2023-06-22",
    "reference_period": "2023–2028",
    "url": "https://projects.worldbank.org/en/projects-operations/project-detail/P179247",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "en",
    "notes": "600 MW, 200 km HVDC undersea cable co-financed by €307.6M EU Connecting Europe Facility grant and $268.4M World Bank financing."
  },
  {
    "source_id": "SRC-ANPE-GABES2018",
    "organization": "Agence Nationale de Protection de l'Environnement (ANPE) / World Bank",
    "title": "Audit Environnemental et Social de la Gestion du Phosphogypse à Gabès (Projet PGSE P118870)",
    "publication_date": "2018-03-15",
    "reference_period": "2018 Benchmark",
    "url": "http://documents.worldbank.org/curated/en/pgse-gabes-audit-2018",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Establishes historical baseline of ~14,000 tonnes/day dry-solid phosphogypsum marine discharge into Gulf of Gabès."
  },
  {
    "source_id": "SRC-JORT-GABES2017",
    "organization": "Prime Ministry of the Republic of Tunisia",
    "title": "Communiqué du Conseil des Ministres du 29 juin 2017 relatif au transfert des unités industrielles du GCT à Gabès",
    "publication_date": "2017-06-29",
    "reference_period": "June 29, 2017",
    "url": "http://www.pm.gov.tn/pm/actualites/cabinet-communique-29-06-2017",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-11",
    "language": "fr",
    "notes": "Government decision pledging dismantling and relocation of GCT chemical processing units away from coastal urban perimeter."
  },
  {
    "source_id": "SRC-JORT-DEC2021-80",
    "organization": "Presidency of the Republic of Tunisia",
    "title": "Décrets présidentiels n° 2021-80 et 2021-81 du 25 juillet 2021, relatifs à la suspension des compétences de l'Assemblée et la fin des fonctions du Chef du Gouvernement",
    "publication_date": "2021-07-26",
    "reference_period": "July 25, 2021",
    "url": "http://www.iort.gov.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Official gazette decrees formalizing Article 80 implementation, assembly suspension, and dismissal of PM Mechichi (JORT n° 64/2021)."
  },
  {
    "source_id": "SRC-JORT-DEC2022-11",
    "organization": "Presidency of the Republic of Tunisia",
    "title": "Décret-loi n° 2022-11 du 12 février 2022, relatif à la création du Conseil supérieur provisoire de la magistrature",
    "publication_date": "2022-02-12",
    "reference_period": "February 12, 2022",
    "url": "http://www.iort.gov.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Dissolved the 2016 elected High Judicial Council and established a provisional executive-appointed council (JORT n° 16/2022)."
  },
  {
    "source_id": "SRC-JORT-DEC2022-13",
    "organization": "Presidency of the Republic of Tunisia",
    "title": "Décret-loi n° 2022-13 du 20 mars 2022, portant sur la réconciliation pénale et l'affectation de ses ressources",
    "publication_date": "2022-03-20",
    "reference_period": "March 20, 2022",
    "url": "http://www.iort.gov.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Created the National Penal Reconciliation Commission to negotiate financial settlements with businessmen and fund regional projects (JORT n° 32/2022)."
  },
  {
    "source_id": "SRC-JORT-DEC2022-22",
    "organization": "Presidency of the Republic of Tunisia",
    "title": "Décret-loi n° 2022-22 du 21 avril 2022, modifiant et complétant la loi organique créant l'Instance supérieure indépendante pour les élections",
    "publication_date": "2022-04-21",
    "reference_period": "April 21, 2022",
    "url": "http://www.iort.gov.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Reorganized the ISIE council, granting the President of the Republic authority to appoint all 7 members (JORT n° 45/2022)."
  },
  {
    "source_id": "SRC-JORT-DEC2022-55",
    "organization": "Presidency of the Republic of Tunisia",
    "title": "Décret-loi n° 2022-55 du 15 septembre 2022, modifiant la loi organique relative aux élections et référendums",
    "publication_date": "2022-09-15",
    "reference_period": "September 15, 2022",
    "url": "http://www.iort.gov.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Introduced two-round uninominal voting in single-member districts, eliminating party lists and introducing recall mechanisms (JORT n° 103/2022)."
  },
  {
    "source_id": "SRC-JORT-DEC2023-8",
    "organization": "Presidency of the Republic of Tunisia",
    "title": "Décrets-lois n° 2023-8, 2023-9 et 2023-10 du 8 mars 2023 relatifs aux conseils municipaux et au Conseil national des régions et des districts",
    "publication_date": "2023-03-08",
    "reference_period": "March 8, 2023",
    "url": "http://www.iort.gov.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Dissolved all 350 elected municipal councils and established the legislative structure for regional and district councils (JORT n° 24/2023)."
  },
  {
    "source_id": "SRC-JORT-LAW2024-10",
    "organization": "Assembly of the Representatives of the People / Presidency of the Republic",
    "title": "Loi n° 2024-10 du 6 février 2024, portant dérogation exceptionnelle aux dispositions de la loi portant fixation des statuts de la Banque Centrale de Tunisie",
    "publication_date": "2024-02-07",
    "reference_period": "February 6, 2024",
    "url": "http://www.iort.gov.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Authorized BCT to grant exceptional direct cash financing of 7 billion TND to the Ministry of Finance without interest for sovereign debt repayment (JORT n° 19/2024)."
  },
  {
    "source_id": "SRC-JORT-LAW2024-45",
    "organization": "Assembly of the Representatives of the People / Presidency of the Republic",
    "title": "Loi n° 2024-45 du 27 septembre 2024, modifiant certaines dispositions de la loi organique relative aux élections et référendums",
    "publication_date": "2024-09-28",
    "reference_period": "September 27, 2024",
    "url": "http://www.iort.gov.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Transferred electoral litigation jurisdiction from the Administrative Court to the Court of Appeal of Tunis nine days before the presidential election (JORT n° 117/2024)."
  },
  {
    "source_id": "SRC-ISIE-PARL2019",
    "organization": "Instance Supérieure Indépendante pour les Élections (ISIE)",
    "title": "Décision de l'ISIE n° 2019-28 fixant les résultats définitifs des élections législatives de 2019",
    "publication_date": "2019-11-08",
    "reference_period": "October 6, 2019",
    "url": "http://www.isie.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "ar",
    "notes": "Certified results of the 2019 parliamentary election: 52 seats Ennahdha, 38 Qalb Tounes, 22 Attayar, 21 Karama, on 41.7% turnout (JORT n° 90/2019)."
  },
  {
    "source_id": "SRC-ISIE-REF2022",
    "organization": "Instance Supérieure Indépendante pour les Élections (ISIE)",
    "title": "Décision de l'ISIE n° 2022-22 relative aux résultats définitifs du référendum du 25 juillet 2022",
    "publication_date": "2022-08-16",
    "reference_period": "July 25, 2022",
    "url": "http://www.isie.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "ar",
    "notes": "Certified 2022 constitutional referendum results: 94.60% Yes (2,607,884 votes), 5.40% No (148,720 votes), on 30.5% turnout (JORT n° 89/2022)."
  },
  {
    "source_id": "SRC-ISIE-PARL2022",
    "organization": "Instance Supérieure Indépendante pour les Élections (ISIE)",
    "title": "Décisions de l'ISIE relatives aux résultats définitifs des élections législatives (Tours 1 et 2)",
    "publication_date": "2023-02-25",
    "reference_period": "Dec 2022 – Jan 2023",
    "url": "http://www.isie.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "ar",
    "notes": "Certified legislative turnout: 11.22% in Round 1 (Dec 17, 2022) and 11.40% in Round 2 (Jan 29, 2023) (JORT n° 20/2023)."
  },
  {
    "source_id": "SRC-TA-RULINGS-2024",
    "organization": "Tribunal Administratif de Tunis (Administrative Court)",
    "title": "Arrêts de l'Assemblée Plénière du Tribunal Administratif sur les recours électoraux",
    "publication_date": "2024-08-30",
    "reference_period": "August 2024",
    "url": "http://www.tribunal-administratif.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "ar",
    "notes": "Definitive appellate judgments ordering the reinstatement of disqualified presidential candidates (Abdellatif Mekki, Mondher Znaidi, Imed Daimi)."
  },
  {
    "source_id": "SRC-SNJT-REPORT2024",
    "organization": "Syndicat National des Journalistes Tunisiens (SNJT)",
    "title": "Rapport Annuel sur la Liberté de la Presse et la Sécurité des Journalistes en Tunisie",
    "publication_date": "2024-05-03",
    "reference_period": "2022–2024",
    "url": "https://snjt.org/rapport-annuel-2024",
    "source_type": "INDEPENDENT",
    "accessed_at": "2026-09-12",
    "language": "ar",
    "notes": "Empirical documentation of over 60 proceedings under Decree-Law 54 Article 24 targeting journalists, media commentators, and lawyers."
  },
  {
    "source_id": "SRC-FTDES-PROTESTS2025",
    "organization": "Forum Tunisien pour les Droits Économiques et Sociaux (FTDES)",
    "title": "Rapport Annuel des Mouvements Sociaux, des Violations et de la Justice Environnementale",
    "publication_date": "2025-01-20",
    "reference_period": "2024–2025",
    "url": "https://ftdes.net/rapport-social-2024",
    "source_type": "INDEPENDENT",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Statistical observatory documenting over 3,000 localized social and hydraulic protests and tracking central Mediterranean interception telemetry."
  },
  {
    "source_id": "SRC-BCT-ANNUAL2024",
    "organization": "Banque Centrale de Tunisie (BCT)",
    "title": "Rapport Annuel de la BCT - 66ème Exercice",
    "publication_date": "2025-07-15",
    "reference_period": "2024 Full Year",
    "url": "https://www.bct.gov.tn/bct/site-box/rapport_annuel.jsp",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Documents monetary expansion, state direct borrowing impact, dinar exchange rate trajectory, and commercial bank liquidity."
  },
  {
    "source_id": "SRC-CPG-STATS2025",
    "organization": "Compagnie des Phosphates de Gafsa (CPG) / Ministry of Industry",
    "title": "Bulletins Statistiques de la Production et du Transport de Phosphate Commercial",
    "publication_date": "2025-02-10",
    "reference_period": "2019–2025",
    "url": "http://www.cpg.com.tn",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Official extraction data documenting actual national production hovering between 3.0M and 3.4M tonnes against 8M tonne annual capacity."
  },
  {
    "source_id": "SRC-MEFP-COMM2025",
    "organization": "Ministère de l'Emploi et de la Formation Professionnelle / TAP",
    "title": "Bulletins de Suivi de la Création des Sociétés Communautaires (2025)",
    "publication_date": "2025-11-15",
    "reference_period": "2025 Cumulative",
    "url": "http://www.emploi.gov.tn/fr/societes-communautaires",
    "source_type": "PRIMARY",
    "accessed_at": "2026-09-12",
    "language": "fr",
    "notes": "Official Ministry of Employment administrative series: 144 created in Feb 2025, 255 with tax identifier (55 operating) in Aug 2025, 236 created (60 operating) by 15 Nov 2025, supported by 95M TND in dedicated credit lines across 2023–2026 finance laws."
  },
]);

export const SOURCE_MAP = Object.freeze(new Map(SOURCE_MANIFEST.map(s => [s.source_id, s])));
